// Mocks generated by Mockito 5.4.5 from annotations
// in tracking_flower_app/test/domain/auth/use_case/login_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i13;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tracking_flower_app/core/utils/datasource_excution/api_result.dart'
    as _i4;
import 'package:tracking_flower_app/data/auth/models/forget_password_request_dto.dart'
    as _i7;
import 'package:tracking_flower_app/data/auth/models/reset_password_request_dto.dart'
    as _i9;
import 'package:tracking_flower_app/data/auth/models/verify_reset_code_request_dto.dart'
    as _i8;
import 'package:tracking_flower_app/domain/auth/entity/apply_request_entity.dart'
    as _i15;
import 'package:tracking_flower_app/domain/auth/entity/country_entity.dart'
    as _i10;
import 'package:tracking_flower_app/domain/auth/entity/login_request_entity.dart'
    as _i5;
import 'package:tracking_flower_app/domain/auth/entity/national_id_entity.dart'
    as _i14;
import 'package:tracking_flower_app/domain/auth/entity/vehicle_license_entity.dart'
    as _i12;
import 'package:tracking_flower_app/domain/auth/entity/vehicles_entity.dart'
    as _i11;
import 'package:tracking_flower_app/domain/auth/repo/auth_repo.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepo extends _i1.Mock implements _i2.AuthRepo {
  MockAuthRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<void>> login(_i5.LoginRequestEntity? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#login, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> forgetPassword(
    _i7.ForgetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [request]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#forgetPassword, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> verifyResetCode(
    _i8.VerifyResetCodeRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [request]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#verifyResetCode, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> resetPassword(
    _i9.ResetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<List<_i10.CountryEntity>> getCountries() =>
      (super.noSuchMethod(
            Invocation.method(#getCountries, []),
            returnValue: _i3.Future<List<_i10.CountryEntity>>.value(
              <_i10.CountryEntity>[],
            ),
          )
          as _i3.Future<List<_i10.CountryEntity>>);

  @override
  _i3.Future<_i4.Result<List<_i11.VehiclesEntity>>> getVehicles() =>
      (super.noSuchMethod(
            Invocation.method(#getVehicles, []),
            returnValue:
                _i3.Future<_i4.Result<List<_i11.VehiclesEntity>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i11.VehiclesEntity>>>(
                    this,
                    Invocation.method(#getVehicles, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i11.VehiclesEntity>>>);

  @override
  _i3.Future<_i4.Result<_i12.VehicleLicenseEntity>>
  extractDataFromVehicleLicense(_i13.File? vehicleLicenseImage) =>
      (super.noSuchMethod(
            Invocation.method(#extractDataFromVehicleLicense, [
              vehicleLicenseImage,
            ]),
            returnValue:
                _i3.Future<_i4.Result<_i12.VehicleLicenseEntity>>.value(
                  _i6.dummyValue<_i4.Result<_i12.VehicleLicenseEntity>>(
                    this,
                    Invocation.method(#extractDataFromVehicleLicense, [
                      vehicleLicenseImage,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i12.VehicleLicenseEntity>>);

  @override
  _i3.Future<_i4.Result<_i14.NationalIdEntity>> extractDataFromNationalId(
    _i13.File? nationalIdImage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#extractDataFromNationalId, [nationalIdImage]),
            returnValue: _i3.Future<_i4.Result<_i14.NationalIdEntity>>.value(
              _i6.dummyValue<_i4.Result<_i14.NationalIdEntity>>(
                this,
                Invocation.method(#extractDataFromNationalId, [
                  nationalIdImage,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i14.NationalIdEntity>>);

  @override
  _i3.Future<_i4.Result<void>> apply(_i15.ApplyRequestEntity? request) =>
      (super.noSuchMethod(
            Invocation.method(#apply, [request]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#apply, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}
