// Mocks generated by Mockito 5.4.5 from annotations
// in tracking_flower_app/test/data/auth/data_source/remote/auth_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tracking_flower_app/data/auth/api/auth_retrofit_client.dart'
    as _i6;
import 'package:tracking_flower_app/data/auth/models/forget_password_request_dto.dart'
    as _i9;
import 'package:tracking_flower_app/data/auth/models/forget_password_response_dto.dart'
    as _i3;
import 'package:tracking_flower_app/data/auth/models/login_request_dto.dart'
    as _i8;
import 'package:tracking_flower_app/data/auth/models/login_response_dto.dart'
    as _i2;
import 'package:tracking_flower_app/data/auth/models/reset_password_request_dto.dart'
    as _i11;
import 'package:tracking_flower_app/data/auth/models/reset_password_response_dto.dart'
    as _i5;
import 'package:tracking_flower_app/data/auth/models/verify_reset_code_request_dto.dart'
    as _i10;
import 'package:tracking_flower_app/data/auth/models/verify_reset_code_response_dto.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponseDto_0 extends _i1.SmartFake
    implements _i2.LoginResponseDto {
  _FakeLoginResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetPasswordResponseDto_1 extends _i1.SmartFake
    implements _i3.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyResetCodeResponseDto_2 extends _i1.SmartFake
    implements _i4.VerifyResetCodeResponseDto {
  _FakeVerifyResetCodeResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseDto_3 extends _i1.SmartFake
    implements _i5.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRetrofitClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRetrofitClient extends _i1.Mock
    implements _i6.AuthRetrofitClient {
  MockAuthRetrofitClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.LoginResponseDto> login(_i8.LoginRequestDto? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i7.Future<_i2.LoginResponseDto>.value(
              _FakeLoginResponseDto_0(
                this,
                Invocation.method(#login, [request]),
              ),
            ),
          )
          as _i7.Future<_i2.LoginResponseDto>);

  @override
  _i7.Future<_i3.ForgetPasswordResponseDto> forgetPassword(
    _i9.ForgetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [request]),
            returnValue: _i7.Future<_i3.ForgetPasswordResponseDto>.value(
              _FakeForgetPasswordResponseDto_1(
                this,
                Invocation.method(#forgetPassword, [request]),
              ),
            ),
          )
          as _i7.Future<_i3.ForgetPasswordResponseDto>);

  @override
  _i7.Future<_i4.VerifyResetCodeResponseDto> verifyResetCode(
    _i10.VerifyResetCodeRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [request]),
            returnValue: _i7.Future<_i4.VerifyResetCodeResponseDto>.value(
              _FakeVerifyResetCodeResponseDto_2(
                this,
                Invocation.method(#verifyResetCode, [request]),
              ),
            ),
          )
          as _i7.Future<_i4.VerifyResetCodeResponseDto>);

  @override
  _i7.Future<_i5.ResetPasswordResponseDto> resetPassword(
    _i11.ResetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i7.Future<_i5.ResetPasswordResponseDto>.value(
              _FakeResetPasswordResponseDto_3(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
          )
          as _i7.Future<_i5.ResetPasswordResponseDto>);
}
