// Mocks generated by Mockito 5.4.5 from annotations
// in tracking_flower_app/test/data/auth/repo_impl/auth_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:tracking_flower_app/core/utils/datasource_excution/api_manager.dart'
    as _i7;
import 'package:tracking_flower_app/core/utils/datasource_excution/api_result.dart'
    as _i8;
import 'package:tracking_flower_app/data/auth/data_source/contract/auth_local_data_source.dart'
    as _i6;
import 'package:tracking_flower_app/data/auth/data_source/contract/auth_remote_data_source.dart'
    as _i3;
import 'package:tracking_flower_app/data/auth/models/login_request_dto.dart'
    as _i5;
import 'package:tracking_flower_app/data/auth/models/login_response_dto.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponseDto_0 extends _i1.SmartFake
    implements _i2.LoginResponseDto {
  _FakeLoginResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i3.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.LoginResponseDto> login(_i5.LoginRequestDto? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i4.Future<_i2.LoginResponseDto>.value(
              _FakeLoginResponseDto_0(
                this,
                Invocation.method(#login, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.LoginResponseDto>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i6.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveToken(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getToken(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getToken, [key]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> deleteToken(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, [key]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setRememberMe(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setRememberMe, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isRememberMe() =>
      (super.noSuchMethod(
            Invocation.method(#isRememberMe, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ApiManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiManager extends _i1.Mock implements _i7.ApiManager {
  MockApiManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i8.Result<T>> execute<T>(_i4.Future<T> Function()? apiCall) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [apiCall]),
            returnValue: _i4.Future<_i8.Result<T>>.value(
              _i9.dummyValue<_i8.Result<T>>(
                this,
                Invocation.method(#execute, [apiCall]),
              ),
            ),
          )
          as _i4.Future<_i8.Result<T>>);
}
