// Mocks generated by Mockito 5.4.5 from annotations
// in tracking_flower_app/test/data/auth/repo_impl/auth_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:tracking_flower_app/core/utils/datasource_excution/api_manager.dart'
    as _i5;
import 'package:tracking_flower_app/core/utils/datasource_excution/api_result.dart'
    as _i7;
import 'package:tracking_flower_app/data/auth/data_source/contract/auth_remote_data_source.dart'
    as _i9;
import 'package:tracking_flower_app/data/auth/models/forget_password_request_dto.dart'
    as _i10;
import 'package:tracking_flower_app/data/auth/models/forget_password_response_dto.dart'
    as _i2;
import 'package:tracking_flower_app/data/auth/models/reset_password_request_dto.dart'
    as _i11;
import 'package:tracking_flower_app/data/auth/models/reset_password_response_dto.dart'
    as _i3;
import 'package:tracking_flower_app/data/auth/models/verify_reset_code_request_dto.dart'
    as _i12;
import 'package:tracking_flower_app/data/auth/models/verify_reset_code_response_dto.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForgetPasswordResponseDto_0 extends _i1.SmartFake
    implements _i2.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseDto_1 extends _i1.SmartFake
    implements _i3.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyResetCodeResponseDto_2 extends _i1.SmartFake
    implements _i4.VerifyResetCodeResponseDto {
  _FakeVerifyResetCodeResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiManager extends _i1.Mock implements _i5.ApiManager {
  MockApiManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i7.Result<T>> execute<T>(_i6.Future<T> Function()? apiCall) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [apiCall]),
            returnValue: _i6.Future<_i7.Result<T>>.value(
              _i8.dummyValue<_i7.Result<T>>(
                this,
                Invocation.method(#execute, [apiCall]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<T>>);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i9.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ForgetPasswordResponseDto> forgetPassword(
    _i10.ForgetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [request]),
            returnValue: _i6.Future<_i2.ForgetPasswordResponseDto>.value(
              _FakeForgetPasswordResponseDto_0(
                this,
                Invocation.method(#forgetPassword, [request]),
              ),
            ),
          )
          as _i6.Future<_i2.ForgetPasswordResponseDto>);

  @override
  _i6.Future<_i3.ResetPasswordResponseDto> resetPassword(
    _i11.ResetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i6.Future<_i3.ResetPasswordResponseDto>.value(
              _FakeResetPasswordResponseDto_1(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
          )
          as _i6.Future<_i3.ResetPasswordResponseDto>);

  @override
  _i6.Future<_i4.VerifyResetCodeResponseDto> verifyResetCode(
    _i12.VerifyResetCodeRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [request]),
            returnValue: _i6.Future<_i4.VerifyResetCodeResponseDto>.value(
              _FakeVerifyResetCodeResponseDto_2(
                this,
                Invocation.method(#verifyResetCode, [request]),
              ),
            ),
          )
          as _i6.Future<_i4.VerifyResetCodeResponseDto>);
}
